services:
  _defaults:
    autowire: true
    autoconfigure: true

  Invenso\DoctrineCleanupMigrations\:
    resource: "../../"
    exclude:
      - "../../InvensoDoctrineCleanupMigrationsBundle.php"
      - "../../DependencyInjection/"
      - "../../Services/"
      - "../../Tests/"
